version: '3'
services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: matatabi
      POSTGRES_PASSWORD: crazycat0010
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: hydra
  meilisearch:
    image: getmeili/meilisearch
    restart: on-failure
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: matatabi

volumes:
  meilisearch-data:
  db-data:
