version: '3'
services:
  mysql_db: 
    image: mysql:5.7.36
    ports:
      - 50986:50986
    volumes:
      - db-data:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: nekomata
      MYSQL_USER: matatabi
      MYSQL_PASSWORD: matatabi
      MYSQL_TCP_PORT: 50986

  meilisearch:
    image: getmeili/meilisearch
    restart: on-failure
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: matatabi

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hydra
  
volumes:
  db-data: 
  meilisearch-data: